### ISSUE TITLE
PHP SDK undefined method Qiniu\Config::getRsHostV2()

### ISSUE THREAD

**Issue by jeanli-mai** [qiniu/php-sdk#400]
## 问题描述

- 代码

```php
function actionTest($fileName) {
    $auth = new Auth(QINIU_ACCESS_KEY, QINIU_SECRET_KEY);
    $bucketMgr = new BucketManager($auth);
    return $bucketMgr->stat($this->bucket, $fileName);
}
```

- 报错

```
Error: Call to undefined method Qiniu\Config::getRsHostV2() in /workspace/project/src/vendor/qiniu/php-sdk/src/Qiniu/Storage/BucketManager.php:1019
Stack trace:
#0 /workspace/project/src/vendor/qiniu/php-sdk/src/Qiniu/Storage/BucketManager.php(608): Qiniu\Storage\BucketManager->rsGet('project-private-...', '/stat/xxxxx...')
#1 /workspace/project/src/backend/components/Qiniu.php(135): Qiniu\Storage\BucketManager->stat('project-private-...', '\xE6\x9C\x83\xE5\x93\xA1\xE5\xB0\x8E\xE5\x87\xBA_20...')
#2 /workspace/project/src/backend/utils/ExcelUtil.php(336): backend\components\Qiniu->test('\xE6\x9C\x83\xE5\x93\xA1\xE5\xB0\x8E\xE5\x87\xBA_20...')
之后还有，但是不方便展示
```

麻烦帮忙看下

## 相关信息

- SDK 版本：v7.7.0
- 框架版本：Yii 2.0.45

**Comment by lihsai0** [comment]
@jeanli-mai 

<img width="406" alt="image" src="https://user-images.githubusercontent.com/17806506/212233163-9b927b14-5ffe-4d68-8d3a-09c801f0708c.png">


您好，久等了，未能复现。

具体代码：

```php
use Qiniu\Auth;
use Qiniu\Storage\BucketManager;

$accessKey = getenv('QINIU_ACCESS_KEY');
$secretKey = getenv('QINIU_SECRET_KEY');
$bucket = getenv('QINIU_TEST_BUCKET');
$key = "qiniu.mp4";

$auth = new Auth($accessKey, $secretKey);
$bucketMgr = new BucketManager($auth);

list($ret, $err) = $bucketMgr->stat($bucket, $key);
if ($err != null) {
    var_dump($err);
} else {
    var_dump($ret);
}

```

输出为：

```
array(6) {
  ["fsize"]=>
  int(25538648)
  ["hash"]=>
  string(28) "lhsawSRA9-0L8b0s-cXmojaMhGqn"
  ["md5"]=>
  string(32) "3e3a14fd770889162c4c5b94b7994cae"
  ["mimeType"]=>
  string(9) "video/mp4"
  ["putTime"]=>
  int(16735803257165241)
  ["type"]=>
  int(0)
}
```

针对您的错误信息，可以看下 `var_dump($bucketMgr);` 的输出中是否有 `["config":"Qiniu\Storage\BucketManager":private]=>object(Qiniu\Config)`

另外，试下手动实例化一个 Config？

```diff
+ use Qiniu\Config;

...

+ $config = new Config();
- $bucketMgr = new BucketManager($auth);
+ $bucketManager = new BucketManager($auth, $config);
```

**Comment by jeanli-mai** [comment]
已解决，原因是 PHP pgcache 没有清理掉，重启一下 supervisor 就可以了
